######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 7 17:18:31 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myqt.h
FORMS += mywin.ui
SOURCES += main.cpp myqt.cpp
